### ISSUE TITLE
Can't use document search

### ISSUE THREAD

**Issue by Fighter19** [kimios/kimios#72]
I've installed "kimios-karaf-distribution-1.2.3"
and I'm using a PostgreSQL database.

```
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1), server 10.19 (Ubuntu 10.19-0ubuntu0.18.04.1))
```

I'm able to add documents, delete documents, add users, assign them to groups etc.
But I'm unable to search.
Trying to search for anything using the web client throws following exception:

```
An exception has occured : Error 08 : Index exception
	at org.kimios.client.exception.ExceptionHelper.convertException(ExceptionHelper.java:57)
	at org.kimios.client.controller.SearchController.advancedSearchDocument(SearchController.java:142)
	at org.kimios.controller.SearchControllerWeb.execute(SearchControllerWeb.java:178)
	at org.kimios.front.MainController.doPost(MainController.java:192)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.kimios.core.filters.CoreFilter.doFilter(CoreFilter.java:56)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.kimios.core.EncodingFilter.doFilter(EncodingFilter.java:40)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devtom30** [comment]
Hi, 
I've just published a new release (with bug fixes). I have tested and I was able to search through documents.
Here is the link to this release: [https://github.com/kimios/kimios/releases/tag/v1.2.5](https://github.com/kimios/kimios/releases/tag/v1.2.5)

**Comment by Fighter19** [comment]
Thank you for your answer.
I've tried the new release, yet the problem persists.
It's throws verbatim the exact same error message.
Maybe I need to recreate the database?

EDIT: Tested again with empty database,
problem persists on my setup.

EDIT2: Maybe my config is faulty?
Does Solr need to be set?
```
export KIMIOS_JDBC_URL="jdbc:postgresql://localhost/kimios"
export KIMIOS_JDBC_USER=kimios
export KIMIOS_JDBC_PASSWORD=kimios
export KIMIOS_REPO_PATH=[LONG PATH TO DRIVE]/data/kimios/
export KIMIOS_REPO_TMP_PATH=[LONG PATH TO DRIVE]/data/kimios/tmp
#export KIMIOS_SOLR_HOME=
#export KIMIOS_SOLR_SERVER_URL=
#export KIMIOS_ZIP_EXPORT_PATH=
```

**Comment by devtom30** [comment]
Hello,
You have to set KIMIOS_SOLR_HOME. It's the location for Solr index and conf files.
Solr needs to be set to allow to search.
